# Generated by Django 4.2.4 on 2023-08-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='search_methods',
            field=models.TextField(blank=True, null=True),
        ),
    ]
